/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CandidateCreateNestedManyWithoutSkillsInput } from "./CandidateCreateNestedManyWithoutSkillsInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { OpportunityWhereUniqueInput } from "../../opportunity/base/OpportunityWhereUniqueInput";
import { SkillLevelCreateNestedManyWithoutSkillsInput } from "./SkillLevelCreateNestedManyWithoutSkillsInput";
import { SkillSetCreateNestedManyWithoutSkillsInput } from "./SkillSetCreateNestedManyWithoutSkillsInput";
@InputType()
class SkillCreateInput {
  @ApiProperty({
    required: false,
    type: () => CandidateCreateNestedManyWithoutSkillsInput,
  })
  @ValidateNested()
  @Type(() => CandidateCreateNestedManyWithoutSkillsInput)
  @IsOptional()
  @Field(() => CandidateCreateNestedManyWithoutSkillsInput, {
    nullable: true,
  })
  candidate?: CandidateCreateNestedManyWithoutSkillsInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: false,
    type: () => OpportunityWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => OpportunityWhereUniqueInput)
  @IsOptional()
  @Field(() => OpportunityWhereUniqueInput, {
    nullable: true,
  })
  opportunity?: OpportunityWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => OpportunityWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => OpportunityWhereUniqueInput)
  @IsOptional()
  @Field(() => OpportunityWhereUniqueInput, {
    nullable: true,
  })
  oppurtunatyRequiredSkills?: OpportunityWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => SkillLevelCreateNestedManyWithoutSkillsInput,
  })
  @ValidateNested()
  @Type(() => SkillLevelCreateNestedManyWithoutSkillsInput)
  @IsOptional()
  @Field(() => SkillLevelCreateNestedManyWithoutSkillsInput, {
    nullable: true,
  })
  skillMatrices?: SkillLevelCreateNestedManyWithoutSkillsInput;

  @ApiProperty({
    required: false,
    type: () => SkillSetCreateNestedManyWithoutSkillsInput,
  })
  @ValidateNested()
  @Type(() => SkillSetCreateNestedManyWithoutSkillsInput)
  @IsOptional()
  @Field(() => SkillSetCreateNestedManyWithoutSkillsInput, {
    nullable: true,
  })
  skillSets?: SkillSetCreateNestedManyWithoutSkillsInput;
}
export { SkillCreateInput };
