import { CommunicationFeedback } from "../communicationFeedback/CommunicationFeedback";
import { RecruitmentPartner } from "../recruitmentPartner/RecruitmentPartner";
import { Interview } from "../interview/Interview";
import { Opportunity } from "../opportunity/Opportunity";
import { User } from "../user/User";
import { Skill } from "../skill/Skill";
import { SkillSet } from "../skillSet/SkillSet";

export type Candidate = {
  additionalComments: string | null;
  category?: "P1" | "P2" | "P3";
  communicationFeedback?: CommunicationFeedback | null;
  competitorCtc: number | null;
  createdAt: Date;
  currentCtc: number | null;
  currentDesignation: string | null;
  currentFirm: string | null;
  currentStatus: string;
  email: string;
  expectedCtc: number | null;
  externalRecruitmentPartner?: RecruitmentPartner | null;
  id: string;
  interviews?: Array<Interview>;
  isOnNoticePeriod: boolean;
  lastWorkingDay: Date | null;
  name: string;
  noticePeriodTime: number | null;
  opportunity?: Opportunity | null;
  referalEmployee?: User | null;
  resume: string | null;
  skills?: Array<Skill>;
  skillSets?: Array<SkillSet>;
  source?: "Internal" | "Referral" | "ExternalRecruitmentPartner";
  totalExperience: number;
  updatedAt: Date;
};
