import { OpportunityUpdateManyWithoutCandidatesInput } from "./OpportunityUpdateManyWithoutCandidatesInput";
import { CommunicationFeedbackWhereUniqueInput } from "../communicationFeedback/CommunicationFeedbackWhereUniqueInput";
import { RecruitmentPartnerWhereUniqueInput } from "../recruitmentPartner/RecruitmentPartnerWhereUniqueInput";
import { InterviewUpdateManyWithoutCandidatesInput } from "./InterviewUpdateManyWithoutCandidatesInput";
import { OpportunityWhereUniqueInput } from "../opportunity/OpportunityWhereUniqueInput";
import { UserWhereUniqueInput } from "../user/UserWhereUniqueInput";
import { SkillUpdateManyWithoutCandidatesInput } from "./SkillUpdateManyWithoutCandidatesInput";
import { SkillSetUpdateManyWithoutCandidatesInput } from "./SkillSetUpdateManyWithoutCandidatesInput";

export type CandidateUpdateInput = {
  additionalComments?: string | null;
  candidateOpportunity?: OpportunityUpdateManyWithoutCandidatesInput;
  category?: "P1" | "P2" | "P3";
  communicationFeedback?: CommunicationFeedbackWhereUniqueInput | null;
  competitorCtc?: number | null;
  currentCtc?: number | null;
  currentDesignation?: string | null;
  currentFirm?: string | null;
  currentStatus?: string;
  email?: string;
  expectedCtc?: number | null;
  externalRecruitmentPartner?: RecruitmentPartnerWhereUniqueInput | null;
  interviews?: InterviewUpdateManyWithoutCandidatesInput;
  isOnNoticePeriod?: boolean;
  lastWorkingDay?: Date | null;
  name?: string;
  noticePeriodTime?: number | null;
  opportunities?: OpportunityUpdateManyWithoutCandidatesInput;
  opportunity?: OpportunityWhereUniqueInput | null;
  referalEmployee?: UserWhereUniqueInput | null;
  resume?: string | null;
  skills?: SkillUpdateManyWithoutCandidatesInput;
  skillSets?: SkillSetUpdateManyWithoutCandidatesInput;
  source?: "Internal" | "Referral" | "ExternalRecruitmentPartner";
  totalExperience?: number;
};
