/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsEnum,
  IsString,
  IsInt,
} from "class-validator";
import { Type } from "class-transformer";
import { EnumOpportunityCurrentStatus } from "./EnumOpportunityCurrentStatus";
import { InterviewCreateNestedManyWithoutOpportunitiesInput } from "./InterviewCreateNestedManyWithoutOpportunitiesInput";
import { SkillCreateNestedManyWithoutOpportunitiesInput } from "./SkillCreateNestedManyWithoutOpportunitiesInput";
import { PartnerWhereUniqueInput } from "../../partner/base/PartnerWhereUniqueInput";
import { SkillSetCreateNestedManyWithoutOpportunitiesInput } from "./SkillSetCreateNestedManyWithoutOpportunitiesInput";
import { EnumOpportunitySource } from "./EnumOpportunitySource";
@InputType()
class OpportunityCreateInput {
  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  claimedPerson?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    enum: EnumOpportunityCurrentStatus,
  })
  @IsEnum(EnumOpportunityCurrentStatus)
  @IsOptional()
  @Field(() => EnumOpportunityCurrentStatus, {
    nullable: true,
  })
  currentStatus?:
    | "Lead"
    | "OpenOppurtunaty"
    | "NotQualifiedLead"
    | "Replacement"
    | "MappedAndAwaitingInterviewSlot"
    | "AwaitingInterviewFeedback"
    | "OnHold"
    | "Won"
    | "Failed"
    | null;

  @ApiProperty({
    required: false,
    type: () => InterviewCreateNestedManyWithoutOpportunitiesInput,
  })
  @ValidateNested()
  @Type(() => InterviewCreateNestedManyWithoutOpportunitiesInput)
  @IsOptional()
  @Field(() => InterviewCreateNestedManyWithoutOpportunitiesInput, {
    nullable: true,
  })
  interviews?: InterviewCreateNestedManyWithoutOpportunitiesInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  mappedPerson?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => SkillCreateNestedManyWithoutOpportunitiesInput,
  })
  @ValidateNested()
  @Type(() => SkillCreateNestedManyWithoutOpportunitiesInput)
  @IsOptional()
  @Field(() => SkillCreateNestedManyWithoutOpportunitiesInput, {
    nullable: true,
  })
  optionalSkillset?: SkillCreateNestedManyWithoutOpportunitiesInput;

  @ApiProperty({
    required: false,
    type: () => PartnerWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PartnerWhereUniqueInput)
  @IsOptional()
  @Field(() => PartnerWhereUniqueInput, {
    nullable: true,
  })
  partner?: PartnerWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  requiredExperience?: number | null;

  @ApiProperty({
    required: false,
    type: () => SkillSetCreateNestedManyWithoutOpportunitiesInput,
  })
  @ValidateNested()
  @Type(() => SkillSetCreateNestedManyWithoutOpportunitiesInput)
  @IsOptional()
  @Field(() => SkillSetCreateNestedManyWithoutOpportunitiesInput, {
    nullable: true,
  })
  requiredSkillset?: SkillSetCreateNestedManyWithoutOpportunitiesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  requirements?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumOpportunitySource,
  })
  @IsEnum(EnumOpportunitySource)
  @IsOptional()
  @Field(() => EnumOpportunitySource, {
    nullable: true,
  })
  source?: "New" | "BackFill" | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  winOdds?: number | null;
}
export { OpportunityCreateInput };
